Clean up mostly related to MOI_wrapper
exanauts/ActiveSetMethods pull request #74
Opened 2020-09-13 03:32 UTC by ssadat

2020-09-13 17:35 UTC, ssadat commented
```
Test Summary:    | Pass  Total
MathOptInterface |  636    636
```

2020-09-14 16:15 UTC, kibaekkim requested changes

2020-09-14 16:15 UTC, kibaekkim commented on src/MOI_wrapper.jl
> +   	set_parameter(model.options, "hessian_approximation", "limited-memory")
Since no implementation is available yet, the default value should be `none`.

2020-09-14 16:15 UTC, kibaekkim commented on src/Parameters.jl
> +    hessian_approximation::String = "Hessian"
Possible values may be `exact`, `limited-memory`, and `none`.

2020-09-14 17:42 UTC, kibaekkim approved these changes

2020-09-14 19:54 UTC, merged